name: Release Test (Dev)
on:
  push:
    branches: [ dev ]   # ✅ dispara só na branch dev

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please-test:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          release-type: maven
          path: Controle-Ponto
          skip-github-release: true        # ✅ evita criar release real
          skip-tag: true                   # ✅ evita criar tag real
          token: ${{ secrets.GITHUB_TOKEN }}
