name: Lint Commit Messages

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: read

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # garante histórico disponível para a action

      - name: Commitlint
        uses: wagoid/commitlint-github-action@v6
        with:
          configFile: .commitlintrc.yml
          commitDepth: 30   # ✅ valida só os 30 commits mais recentes
          failOnWarnings: false  # opcional: não falhar em warnings
