name: Lint Commit Messages

on:
  pull_request:
    branches: [main, dev]
    types: [opened, synchronize, reopened, edited]

permissions:
  contents: read
  pull-requests: read

jobs:
  commitlint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Precisamos do histórico para a action decidir o recorte por commitDepth
          fetch-depth: 0

      - name: Commitlint (validate recent commits only)
        uses: wagoid/commitlint-github-action@v6
        with:
          # Use este arquivo se você tiver regras customizadas (ver abaixo)
          configFile: .commitlintrc.yml
          # 🔒 Limita a verificação aos commits mais recentes do PR
          commitDepth: 28
          # Opcional: evita falhar em avisos
          failOnWarnings: false
